---
title: "vignette-041-market-plot"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette-041-market-plot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(slfrsk)
load_all()
```

# Market Size
## countries
Value units are 1000 USD
```{r FAO wine market}
data("countries_market")

dim(countries_market)

countries_wine_market <- countries_market %>%
  #filter(is.na(Flag)) %>%
  filter(!is.na(Value)) %>%
  filter(Year %in% (2012:2017)) %>%
  filter(Element == "Export Value") %>%
  group_by(`Area Code`,	Area, Year) %>%
  dplyr::select(`Area Code`,	Area, Year, Value) %>% 
  summarise(market_size = sum(Value)) %>%
  ungroup(Year) %>%
  mutate(market_size = log10((market_size*1000)+1)) %>%
  #mutate(market_size = (market_size*1000)) %>%
  summarise(market_size = mean(market_size))  %>% 
  ungroup()

# remove all that are zero

countries_wine_market$market_size[countries_wine_market$market_size==0] <- NA
dim(countries_wine_market)
#countries_wine_market

qplot(countries_wine_market$market_size)

```


```{r join market to countries_summary_future}

# recode the market ids to match countries_summary_future

countries_wine_market <- countries_wine_market %>%
  mutate(ID = Area) %>%
  mutate(
    ID = recode(
      ID,
      `Bolivia (Plurinational State of)` = "Bolivia",
      `Brunei Darussalam` = "Brunei",
      `Cabo Verde` = "Cape Verde",
      `China, mainland` = "China",
      Congo = "Republic of Congo",
      `Falkland Islands (Malvinas)` = 'Falkland Islands',
      `China, Hong Kong SAR` = "Hong Kong",
      `Iran (Islamic Republic of)` = "Iran",
      `Côte d'Ivoire` = "Ivory Coast",
      `Democratic People's Republic of Korea` = "North Korea",
      `Republic of Korea` = "South Korea",
      `Lao People's Democratic Republic` = "Laos",
      `China, Macao SAR` = "Macao",
      `Republic of Moldova` = "Moldova",
      `Netherlands Antilles (former)` = "Bonaire, Sint Eustatius and Saba",
      `North Macedonia` = "Macedonia",
      Czechia = "Czech Republic",
      `Russian Federation` = "Russia",
      `Syrian Arab Republic`  = "Syria",
      `China, Taiwan Province of` = "Taiwan",
      `United Republic of Tanzania` = "Tanzania",
      `United Kingdom of Great Britain and Northern Ireland` = "United Kingdom",
      `United States of America` = "United States",
      `Venezuela (Bolivarian Republic of)` = "Venezuela",
      `Viet Nam` = "Vietnam",
      Palestine = "Palestina",
      Eswatini = "Swaziland"
      
    )
  ) %>% dplyr::select(ID, market_size) 

#setdiff(countries_summary_future$ID, countries_wine_market$ID)
#setdiff(countries_wine_market$ID, countries_summary_future$ID)

```

```{r}
data("countries_summary_future")

countries_risk_market <- countries_summary_future %>% 
  left_join(countries_wine_market, by = "ID") #%>% 
  #dplyr::select(ID, 
  #              market_size,
  #              log10_avg_prod, 
  #              log10_avg_infected_mass, 
  #              grand_mean_max)

risk_mod <- lm(log10_avg_prod ~ log10_avg_infected_mass + grand_mean_max, data = countries_risk_market)
cor.test(countries_risk_market$log10_avg_prod, predict(risk_mod))


plot(risk_mod)
summary(risk_mod)

countries_risk_market <- countries_risk_market %>%
  mutate(risk = scales::rescale(predict(risk_mod), to = c(1,10)))

shock_mod <- lm(market_size ~ risk, data = countries_risk_market)
summary(shock_mod)

cor.test(countries_risk_market$market_size, countries_risk_market$risk)
shock_cor <- cor(countries_risk_market$market_size, 
                 countries_risk_market$risk,
                 use = "complete.obs") %>% 
  scales::rescale(to = c(1,10), from = c(-1,1)) %>%
  round()
#scales::rescale(-1, to = c(1,10), from = c(-1,1))
```
## Risk
The Risk of SLF to shock the global wine market is `r shock_cor`.


```{r}

countries_risk_market %>%
  mutate(risk_scale = scale(risk), market_size_scale = scale(market_size)) %>%
  #mutate(risk_scale_ticks = )
  ggplot(mapping = aes(x = risk_scale, y = market_size_scale)) +
  geom_point() + 

  


countries_risk_market %>%
  ggplot(mapping = aes(x = (risk), y = (market_size), size = avg_wine)) +
  geom_point(fill = "white") + 
  geom_abline(slope = 1, intercept = 0) + 
  scale_x_continuous("Country Invasion Risk", breaks = 1:10, limits = c(1,10)) +
  scale_y_continuous("Wine Export Market Size", breaks = seq(1,10,1), limits = c(1,10)) +
  scale_size_manual(
        #values = c(0,),
        name = "Wine Production",# "Wine Impact Potential",
        labels = c("0L", "1")
      ) +
      theme(
        panel.grid.major = element_line(colour = "#f0f0f0"),
        panel.grid.minor = element_blank(),
        #panel.grid.major = element_blank(),
        #panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.line = element_line(colour = "black"),
        #legend.position = c(0.7, 0.25),
        #legend.position = "bottom",
        panel.background = element_blank(),
        plot.background = element_blank(),
        legend.background = element_blank(),#element_rect(colour = 'black', fill = 'white', linetype='solid'),
        axis.text = element_text(size = rel(1)),
        axis.title.x = element_text(hjust = .4),
        axis.title.y = element_text(hjust = .35),
        legend.title = element_text(face = "plain"),
        legend.key.size = unit(0.2, "cm"),
        legend.key = element_blank(),
        #plot.margin = unit(c(hh, -5, hh, hh), units = "line"),
        #axis.title = element_text(size = rel(1.3))
      )

```

