---
title: "vignette-030-risk-maps"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette-030-risk-maps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Setup

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, results='hide', message=FALSE}
library(slfrsk)
library(tidyverse)
library(rgeos)
library(scales)
```

Should we assume present infected US states or project future ones?
```{r present switch}
#we need a switch for this map that does the same thing for including the following states: New York, Ohio, West Virginia, North Carolina
present_switch <- FALSE
# How many countries and states to highlight for labels?
top_to_plot <- 10 

```


```{r read in the data we need}
#location of wineries (US and COUNTRIES)
data("wineries")
#need usa enviro raster
data("suitability_usa_df")
data("suitability_countries_df")
#state centers for plot
data("states_centers")
data("countries_centers")

```

# Code and Plots

## States

separate conditional chunk for states trade data to clean it for the plotting
```{r states trade}
#need states trade data
#need to read in trade data to shape network in map figure
if(present_switch == TRUE){
  data("states_summary_present")
  states_centers <- states_centers %>%
    #remove the invaded states
    filter(!geopol_unit %in% c("Delaware", "Maryland", "New Jersey", "Pennsylvania", "Virginia")) %>%
    #remove the others in the dataset
    filter(!is.na(x), !is.na(y)) %>%
    rbind(c("SLF", NA, 40.400189, -75.917622)) %>%
    mutate(x = as.numeric(x), y = as.numeric(y))
  
#now add the "invaded core" == SLF as a column
states_summary_present <- states_summary_present %>%
  cbind("SLF", .) %>%
  as_tibble() %>%
  mutate(origin = `"SLF"`) %>%
  dplyr::select(-`"SLF"`) %>%
  dplyr::select(origin, everything())

#now merge the coords for destinations (ONLY WINE PRODUCING STATES)
states_trade_final <- left_join(states_summary_present, states_centers, by = "geopol_unit") %>%
  filter(!is.na(x), !is.na(y))

#add the coords for SLF as a separate set of cols
states_trade_final <- states_centers %>%
  filter(geopol_unit == "SLF") %>%
  dplyr::select(x,y) %>%
  mutate(xend = x, yend = y) %>%
  dplyr::select(xend, yend) %>%
  cbind(states_trade_final, .) %>%
  as_tibble()
  
} else {
  data("states_summary_future")
  
    states_centers <- states_centers %>%
    #remove the invaded states
    filter(!geopol_unit %in% c("Delaware", "Maryland", "New Jersey", "New York", "North Carolina", "Ohio", "Pennsylvania", "Virginia", "West Virginia")) %>%
    #remove the others in the dataset
    filter(!is.na(x), !is.na(y)) %>%
    rbind(c("SLF", NA, 40.400189, -75.917622)) %>%
    mutate(x = as.numeric(x), y = as.numeric(y))

        #now add the "invaded core" == SLF as a column
    states_summary_future <- states_summary_future %>%
      cbind("SLF", .) %>%
      as_tibble() %>%
      mutate(origin = `"SLF"`) %>%
      dplyr::select(-`"SLF"`) %>%
      dplyr::select(origin, everything())
    
    #now merge the coords for destinations (ONLY WINE PRODUCING STATES)
    states_trade_final <- left_join(states_summary_future, states_centers, by = "geopol_unit") %>%
      filter(!is.na(x), !is.na(y))
    
    #add the coords for SLF as a separate set of cols
    states_trade_final <- states_centers %>%
      filter(geopol_unit == "SLF") %>%
      dplyr::select(x,y) %>%
      mutate(xend = x, yend = y) %>%
      dplyr::select(xend, yend) %>%
      cbind(states_trade_final, .) %>%
      as_tibble()

    }

```

Now plot the states
```{r the US map, fig.height= 6.5, fig.width=7.5}

#plot just the states and suitability first
map_plot <- ggplot() +
  geom_raster(data = suitability_usa_df, aes(x = x, y = y, fill = rescale(value)), alpha=0.9, show.legend = T) +
  scale_fill_gradientn(limits= c(0,1), name = "Suitability", colors = rev(c("#e31a1c","#fd8d3c", "#fecc5c", "#FFFFFF"))) +
  geom_polygon(data = map_data('state'), aes(x = long, y = lat, group = group), fill = NA, color = "black", lwd = 0.10) +
  theme_bw() +
  labs(x = "", y = "") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  coord_quickmap(xlim = c(-124.7628, -66.94889), ylim = c(24.52042, 49.3833)) +
  ggtitle(label = "")

#add in lines for the infected states
if(present_switch == TRUE){
  map_plot <- map_plot +
    geom_polygon(data = map_data('state', c("Delaware", "Maryland", "New Jersey", "Pennsylvania", "Virginia")), aes(x = long, y = lat, group = group), fill = NA, color = "#e31a1c", lwd = 0.75)
  
} else{
  map_plot <- map_plot +
    geom_polygon(data = map_data('state', c("Delaware", "Maryland", "New Jersey", "New York", "North Carolina", "Ohio", "Pennsylvania", "Virginia", "West Virginia")), aes(x = long, y = lat, group = group), fill = NA, color = "#e31a1c", lwd = 0.75)
}

#add in the wine AVA data
map_plot <- map_plot +
    geom_point(data = wineries %>% filter(Country == "United States"), aes(x = x, y = y), color = "black", fill = "purple", size = 1.5, shape = 21, alpha = 0.99, show.legend = F)

#add in the trade
map_plot <- map_plot +
    geom_curve(aes(x = x, y = y, xend = xend, yend = yend), data = states_trade_final %>%  arrange(desc(avg_infected_mass)) %>% .[1:top_to_plot,], size = 1, curvature = 0.33, alpha = 0.8, show.legend = T, color = "#778899",
               arrow = arrow(ends = "first", length = unit(0.01, "npc"), type = "closed"))

#show it
map_plot

```

## Countries

separate conditional chunk for states trade data to clean it for the plotting
```{r countries trade, message=FALSE}

#edit the world centers to also have the SLF US invasion point
countries_centers <- countries_centers %>%
  #rm the others in the dataset
  filter(!is.na(x), !is.na(y)) %>%
  #add center for SLF invasion in US
  #rbind(c("SLF", NA, -75.917622, 40.400189)) %>%
  rbind(c(rep("SLF", times = 4), -75.917622, 40.400189)) %>%  #(x,y) for coords
  #add the netherlands, not a wine country but needs a set of coords
  #rbind(c("Netherlands", NA, unlist(gCentroid(SpatialPointsDataFrame(map_data('world')[map_data('world')$region %in% "Netherlands",1:2], data = map_data('world')[map_data('world')$region %in% "Netherlands",]))@coords))) %>%
  #same for indonesia
  #rbind(c("Indonesia", NA, unlist(gCentroid(SpatialPointsDataFrame(map_data('world')[map_data('world')$region %in% "Indonesia",1:2], data = map_data('world')[map_data('world')$region %in% "Indonesia",]))@coords))) %>%
  #same for these if going for top 25: Singapore, Taiwan, Saudi Arabia, Vietnam, Venezuela, Gibraltar
  #mutate(x = as.numeric(x), y = as.numeric(y), avg_wine = as.numeric(avg_wine))
  mutate(x = as.numeric(x), y = as.numeric(y))

#now we manually bump Canada's coords up a little bit to make more visible
countries_centers$y[countries_centers$geopol_unit == "Canada"] <- countries_centers$y[countries_centers$geopol_unit == "Canada"] + 5


if(present_switch == TRUE){
  data("countries_summary_present")
  
  #filter out the countries with SLF
  countries_summary_present <- countries_summary_present %>%
  filter(!geopol_unit %in% c("China", "Japan", "Korea, South", "India")) %>%
  cbind("SLF", .) %>%
  as_tibble() %>%
  mutate(origin = `"SLF"`) %>%
  dplyr::select(-`"SLF"`) %>%
  dplyr::select(origin, everything())
  
  #now merge the coords for destinations (ONLY WINE PRODUCING countries)
countries_trade_final <- left_join(countries_summary_present, countries_centers, by = "geopol_unit") %>%
  filter(!is.na(x), !is.na(y))


} else {
  data("countries_summary_future")
  
  #filter out the countries with SLF
  countries_summary_future <- countries_summary_future %>%
  filter(!geopol_unit %in% c("China", "Japan", "Korea, South", "India")) %>%
  cbind("SLF", .) %>%
  as_tibble() %>%
  mutate(origin = `"SLF"`) %>%
  dplyr::select(-`"SLF"`) %>%
  dplyr::select(origin, everything())

    #now merge the coords for destinations (ONLY WINE PRODUCING countries)
countries_trade_final <- left_join(countries_summary_future, countries_centers) %>%
  filter(!is.na(x), !is.na(y))
  
}

#add the coords for SLF as a separate set of cols
countries_trade_final <- countries_centers %>%
  filter(geopol_unit == "SLF") %>%
  dplyr::select(x,y) %>%
  mutate(xend = x, yend = y) %>%
  dplyr::select(xend, yend) %>%
  cbind(countries_trade_final, .) %>%
  as_tibble()

```

Now plot the countries

```{r plot map of countries, warning=FALSE, fig.height= 6.5, fig.width=7.5}
#plot just the countries and suitability first
map_plot_countries <- ggplot() +
  geom_raster(data = suitability_countries_df, aes(x = x, y = y, fill = rescale(value)), alpha=0.9, show.legend = T) +
  scale_fill_gradientn(limits= c(0,1), name = "Suitability", colors = rev(c("#e31a1c","#fd8d3c", "#fecc5c", "#FFFFFF"))) +
  geom_polygon(data = map_data('world'), aes(x = long, y = lat, group = group), fill = NA, color = "black", lwd = 0.15) +
  theme_bw() +
  labs(x = "", y = "") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  coord_quickmap(xlim = c(-164.5, 163.5), ylim = c(-55,85)) +
  ggtitle(label = "")
  
#add in lines for the infected states
if(present_switch == TRUE){
  map_plot_countries <- map_plot_countries +
    geom_polygon(data = map_data('state', c("Delaware", "Maryland", "New Jersey", "Pennsylvania", "Virginia")), aes(x = long, y = lat, group = group), fill = NA, color = "red", lwd = 0.5)
} else{
  map_plot_countries <- map_plot_countries +
    geom_polygon(data = map_data('state', c("Delaware", "Maryland", "New Jersey", "New York", "North Carolina", "Ohio", "Pennsylvania", "Virginia", "West Virginia")), aes(x = long, y = lat, group = group), fill = NA, color = "#e31a1c", lwd = 0.75)
}
  

#add in the wine AVA data (global equivalent)
map_plot_countries <- map_plot_countries +
  geom_point(data = wineries, aes(x = x, y = y), color = "black", fill = "purple", size = 0.5, shape = 21, alpha = 0.99, stroke = 0.2, show.legend = F)

#add in the trade
map_plot_countries <- map_plot_countries +
  geom_curve(aes(x = x, y = y, xend = xend, yend = yend), data = countries_trade_final %>%  arrange(desc(avg_infected_mass)) %>% .[1:top_to_plot,], size = 0.45, curvature = 0.33, alpha = 0.8, show.legend = T, color = "#778899", arrow = arrow(ends = "first", length = unit(0.01, "npc"), type = "closed")) 

#print it
map_plot_countries 
```

# Write plot output

```{r save map plots}
if(present_switch){
#states
  ggsave(plot = map_plot, filename = file.path(here::here(),"vignettes", paste0("states_map_present.pdf")), width = 7.5, height = 6.5, dpi = 300)
#countries
  ggsave(plot = map_plot_countries, filename = file.path(here::here(),"vignettes", paste0("countries_map_present.pdf")), width = 7.5, height = 6.5, dpi = 300)
} else{
  #states
  ggsave(plot = map_plot, filename = file.path(here::here(),"vignettes", paste0("states_map_future.pdf")), width = 7.5, height = 6.5, dpi = 300)
#countries
  ggsave(plot = map_plot_countries, filename = file.path(here::here(),"vignettes", paste0("countries_map_future.pdf")), width = 7.5, height = 6.5, dpi = 300)

}

```
